### PR TITLE
updated UI, Added facebook, twitter & google login

### PR DESCRIPTION
**Pull request by Ritsz123**
#1

### CODE REVIEW

**Comment by vaibhav-jain18** [comment]
I need to check this code for this I will need API keys. Can you provide me that?

**Comment by Ritsz123** [comment]
> I need to check this code for this I will need API keys. Can you provide me that?

I used the previous keys that were already present in the project

**Comment by Ritsz123** [comment]
> > I need to check this code for this I will need API keys. Can you provide me that?
> 
> I used the previous keys that were already present in the project

Also you will need to create new firebase project to make the app run. This needs to be updated in Readme.md

**Comment by vaibhav-jain18** [comment]
It is throwing an error.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\Vaibhav Jain\Documents\GitHub\Social media integration app\android\app\src\nullnull\google-services.json
  C:\Users\Vaibhav Jain\Documents\GitHub\Social media integration app\android\app\src\debug\google-services.json
  C:\Users\Vaibhav Jain\Documents\GitHub\Social media integration app\android\app\src\nullnullDebug\google-services.json
  C:\Users\Vaibhav Jain\Documents\GitHub\Social media integration app\android\app\src\nullnull\debug\google-services.json
  C:\Users\Vaibhav Jain\Documents\GitHub\Social media integration app\android\app\src\debug\nullnull\google-services.json
  C:\Users\Vaibhav Jain\Documents\GitHub\Social media integration app\android\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by Ritsz123** [comment]
> * t
did you added google-services.json file?

**Comment by Ritsz123** [comment]
> It is throwing an error.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:processDebugGoogleServices'.
> 
> > File google-services.json is missing. The Google Services Plugin cannot function without it.
> > Searched Location:
> > C:\Users\Vaibhav Jain\Documents\GitHub\Social media integration app\android\app\src\nullnull\google-services.json
> > C:\Users\Vaibhav Jain\Documents\GitHub\Social media integration app\android\app\src\debug\google-services.json
> > C:\Users\Vaibhav Jain\Documents\GitHub\Social media integration app\android\app\src\nullnullDebug\google-services.json
> > C:\Users\Vaibhav Jain\Documents\GitHub\Social media integration app\android\app\src\nullnull\debug\google-services.json
> > C:\Users\Vaibhav Jain\Documents\GitHub\Social media integration app\android\app\src\debug\nullnull\google-services.json
> > C:\Users\Vaibhav Jain\Documents\GitHub\Social media integration app\android\app\google-services.json
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 5s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)

did you added updated google-services.json file?

**Comment by vaibhav-jain18** [comment]
Yes I have added google-services.json file but it is showing that

**Comment by Ritsz123** [comment]
> Yes I have added google-services.json file but it is showing that

You need to get the configuration file from the firebase and paste it in the app level directory of the project. I think you added it in _project\android\app\src_ add it to _**project\android\app**_

**Comment by vaibhav-jain18** [comment]
It is showing this
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_twitter_login-1.1.0\android\src\main\java\com\roughike\fluttertwitterlogin\fluttertwitterlogin\TwitterLoginPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by Ritsz123** [comment]
> It is showing this
> Note: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\flutter_twitter_login-1.1.0\android\src\main\java\com\roughike\fluttertwitterlogin\fluttertwitterlogin\TwitterLoginPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.

wait some time it will run

**Comment by vaibhav-jain18** [comment]
It has run but not working, any login is not working

**Comment by Ritsz123** [comment]
> It has run but not working, any login is not working

make sure to enable google, facebook, twitter authentication in firebase console's sign in methods under authentication tab.

**Comment by vaibhav-jain18** [comment]
I enabled the authentication from firebase console but it is still not working.

**Comment by vaibhav-jain18** [comment]
I have merged your pr but login is not working.

**Comment by Ritsz123** [comment]
check the new readme.md & close #1 this issue

**Pull request merged**
